### ISSUE TITLE
TypeError: this.cssClasses(...).set is not a function

### ISSUE THREAD

**Issue by jahidshohel** [NativeScript/NativeScript#2570]
Getting this error after upgrading to 2.2 (http://stackoverflow.com/questions/38906245/nativescript-2-2-exception).

Occurs both on Android (on my Galaxy S7 edge) and iOS (on emulator).

**Comment by enchev** [comment]
Hey @jahidshohel,

Please check this thread for more info: http://stackoverflow.com/questions/38906245/nativescript-2-2-exception
