### ISSUE TITLE
tns run ios got error Framework "lb:not found AmPopTip"

### ISSUE THREAD

**Issue by PetroSuch** [NativeScript/NativeScript#8959]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: {
  "nativescript": {
    "id": "com.test.app",
    "tns-ios": {
      "version": "6.5.0"
    },
    "tns-android": {
      "version": "6.5.3"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/http": "~8.0.0-beta.10",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@nativescript/schematics": "^0.6.0",
    "@nativescript/theme": "^2.3.3",
    "@nstudio/nativescript-checkbox": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@tweenjs/tween.js": "^17.4.0",
    "lodash": "^4.17.15",
    "lodash.round": "^4.0.4",
    "moment": "^2.24.0",
    "nativescript-angular": "^8.21.0-next-2020-02-17-115749-01",
    "nativescript-background-http": "^4.2.1",
    "nativescript-barcodescanner": "^3.3.2",
    "nativescript-camera": "^4.5.0",
    "nativescript-contacts-lite": "^0.2.6",
    "nativescript-datetimepicker": "^1.2.2",
    "nativescript-dom": "^2.0.5",
    "nativescript-fancyalert": "^3.0.9",
    "nativescript-fingerprint-auth": "^7.0.1",
    "nativescript-gif": "^4.0.5",
    "nativescript-google-maps-sdk": "^2.9.1",
    "nativescript-i18n": "^0.4.1",
    "nativescript-imagecropper": "^3.0.0",
    "nativescript-imagepicker": "^7.1.0",
    "nativescript-iqkeyboardmanager": "^1.5.1",
    "nativescript-keyboard-toolbar": "^1.1.0",
    "nativescript-local-notifications": "^4.1.5",
    "nativescript-localize": "^4.2.2",
    "nativescript-localstorage": "^2.0.1",
    "nativescript-masked-text-field": "^4.0.3",
    "nativescript-md5": "^1.0.1",
    "nativescript-permissions": "^1.3.9",
    "nativescript-phone": "^1.4.1",
    "nativescript-plugin-badge": "^1.0.0",
    "nativescript-plugin-firebase": "^10.3.3",
    "nativescript-pulltorefresh": "^2.3.0",
    "nativescript-secure-storage": "^2.6.0",
    "nativescript-socketio": "^3.3.1",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-toast": "^2.0.0",
    "nativescript-toasty": "^3.0.0-alpha.2",
    "nativescript-tooltip": "^2.1.2",
    "nativescript-ui-chart": "^7.1.1",
    "nativescript-ui-listview": "^8.0.2-next-2019-12-18-091654-01",
    "nativescript-ui-sidedrawer": "^8.0.1",
    "nativescript-uuid": "0.0.1",
    "nativescript-zxing": "^1.5.9",
    "ng2-translate": "^5.0.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-android": "^6.1.2",
    "tns-core-modules": "^6.5.15",
    "tns-ios": "^6.1.1",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "@ngtools/webpack": "8.2.0",
    "@types/lodash": "^4.14.136",
    "nativescript-dev-webpack": "^1.5.1",
    "tns-platform-declarations": "^6.1.2",
    "typescript": "~3.5.3"
  },
  "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
  "readme": "NativeScript Application"
}

 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime: iOS version 13.7
 - Plugin(s):

**Describe the bug**
i got error in my terminal, after run command tns run ios
i have a sertificate and provision file, my app worked successfull, but now i can not run my app on my iphone

Saving metadata generation's stderr stream to: /Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/metadata-generation-stderr-arm64.txt

~/Desktop/hoop_app/hoop/platforms/ios

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/AMPopTip'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/DKCarouselView'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FLAnimatedImage'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FirebaseAuth'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FirebaseCore'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FirebaseCoreDiagnostics'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FirebaseFunctions'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FirebaseInstallations'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FirebaseInstanceID'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/FirebaseMessaging'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/GTMSessionFetcher'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/GoogleDataTransport'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/GoogleDataTransportCCTSupport'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/GoogleUtilities'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/IQKeyboardManager'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/MDFInternationalization'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/MMNumberKeyboard'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/MaterialComponents'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/PromisesObjC'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/Protobuf'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/QBImagePickerController'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/SAMKeychain'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/SBToaster'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/SCLAlertView-Objective-C'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/SSKeychain'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/Socket.IO-Client-Swift'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/Starscream'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/Toast-Swift'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/ZXingObjC'

ld: warning: directory not found for option '-F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos/nanopb'

ld: framework not found AMPopTip

clang: error: linker command failed with exit code 1 (use -v to see invocation)

note: Using new build system

note: Building targets in parallel

note: Planning build

note: Constructing build description

** ARCHIVE FAILED **

Unable to apply changes on device: 97419a29c15bcffd90b08ae5835c142a049a8fe2. Error is: Command xcodebuild failed with exit code 65.

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by eltharynd** [comment]
You're using https://github.com/andreamazz/AMPopTip
But it doesn't "just work" with nativescript.. you can manually add it to your project after preparing the xcode project or https://nativescript.org/faq/how-do-i-use-cocoapods-in-my-nativescript-app/

**Comment by NathanaelA** [comment]
This actually might be related to the XCode version.  If you are continuing to using XCode 11; you must use NS 6 CLI 6.8.0 (or later 6.x versions), if you are using XCode 12 you must use NS 7 CLI 7.0.10 (or later).    

NS 7 CLI is Backwards compatible and will still build NS 6 `tns-core-modules` apps.

**Comment by farfromrefug** [comment]
I think I had a similar issue yesterday. For I it was that I was using tns-ios 6.5.2. Upgrading to 6.5.3, clearing all , building made it work

**Comment by PetroSuch** [comment]
After run command tnr run ios i can not see framework in folder by path hoop\platforms\ios\build\Debug-iphoneos
All framework and AmPopTip locate in other folder platforms\ios\Pods

**Comment by PetroSuch** [comment]
> You're using https://github.com/andreamazz/AMPopTip
> But it doesn't "just work" with nativescript.. you can manually add it to your project after preparing the xcode project or https://nativescript.org/faq/how-do-i-use-cocoapods-in-my-nativescript-app/

i am using this framework like plugin nativescript-tooltip, and the plugin  nativescript-tooltip already includes the framework AmPopTip

the error when not found frameworks happened with my all plugins for nativescript, because i dont understand why framework for these plugin not install in folder by path "F/Users/taraskochubey/Desktop/hoop_app/hoop/platforms/ios/build/Debug-iphoneos"

**Comment by PetroSuch** [comment]
/Users/taraskochubey/Desktop/hoop_app/hoopmerchant/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:20:9: error: 
      double-quoted include "pb.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb.h"
        ^~~~~~
        <pb.h>
/Users/taraskochubey/Desktop/hoop_app/hoopmerchant/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:21:9: error: 
      double-quoted include "pb_encode.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_encode.h"
        ^~~~~~~~~~~~~
        <pb_encode.h>
/Users/taraskochubey/Desktop/hoop_app/hoopmerchant/platforms/ios/Pods/Target Support Files/nanopb/nanopb-umbrella.h:22:9: error: 
      double-quoted include "pb_common.h" in framework header, expected angle-bracketed instead
      [-Werror,-Wquoted-include-in-framework-header]
#import "pb_common.h"
        ^~~~~~~~~~~~~
        <pb_common.h>
13 errors generated.
In file included from /Users/taraskochubey/Desktop/hoop_app/hoopmerchant/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.c:20:
/Users/taraskochubey/Desktop/hoop_app/hoopmerchant/platforms/ios/Pods/GoogleDataTransportCCTSupport/GoogleDataTransportCCTSupport/GDTCCTLibrary/Protogen/nanopb/cct.nanopb.h:22:10: fatal error: 
      could not build module 'nanopb'
#include <nanopb/pb.h>
 ~~~~~~~~^
14 errors generated.
note: Using new build system
note: Building targets in parallel
note: Planning build
note: Constructing build description
warning: MobileCoreServices has been renamed. Use CoreServices instead. (in target 'FLAnimatedImage' from project 'Pods')
** ARCHIVE FAILED **

Unable to apply changes on device: 97419a29c15bcffd90b08ae5835c142a049a8fe2. Error is: Command xcodebuild failed with exit code 65.

after update platform iOS to 6.5.3 I get this error, the problem still alive, and my application does not work,

my tans info showed me this:

You are using the deprecated nsconfig.json file. Just be aware that NativeScript 7 has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.10 version and is up to date.
⚠ Update available for component tns-core-modules. Your current version is 6.5.15 and the latest available version is 6.5.20.
✔ Component tns-ios has 6.5.3 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.

**Comment by PetroSuch** [comment]
**and the ins doctor command showed me that**
You are using the deprecated nsconfig.json file. Just be aware that NativeScript 7 has an improved nativescript.config.(js|ts) file for when you're ready to upgrade this project.
✔ Getting environment information 

TIP: To avoid setting up the necessary environment variables, you can use the Homebrew package manager to install the Android SDK and its dependencies.

```
There seem to be issues with your configuration.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 7.0.10 version and is up to date.
⚠ Update available for component tns-core-modules. Your current version is 6.5.15 and the latest available version is 6.5.20.
✔ Component tns-ios has 6.5.3 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 11.7.0 satisfies minimum required version 10.
```

**Comment by PetroSuch** [comment]
i also update tns-core-modules but i still have many errors `"double-quoted include "pb_encode.h" in framework header, expected angle-bracketed instead"`

**Comment by PetroSuch** [comment]
I add attach with full log of build
[log.txt](https://github.com/NativeScript/NativeScript/files/5371467/log.txt)

**Comment by NathanaelA** [comment]
One thing to check is: https://nativescript.org/blog/nativescript-6-7-xcode-compatibility/ 
If you are using the wrong CLI with the wrong XCode, you will get weird errors like this.   So please read this blog article and verify you are using the proper versions...

**Comment by PetroSuch** [comment]
Could i downgrade nativescript and tns-core-modules from my project for XCode 11.7 ?

**Comment by ihor-lev** [comment]
Possible solution. 1) Open a generated project in Xcode (platforms/ios - blue one not white, with a project name + pods). 2) Menu: File > Workspace settings > Build System -- select "Legacy build system". 3) Rebuild the project in CLI.

**Comment by PetroSuch** [comment]
I can not trying it now, because i reinstalled my MacOS Virtual Machine, and now i can building my project successfully

**Comment by PetroSuch** [comment]
> Possible solution. 1) Open a generated project in Xcode (platforms/ios - blue one not white, with a project name + pods). 2) Menu: File > Workspace settings > Build System -- select "Legacy build system". 3) Rebuild the project in CLI.

Hi @ihor-lev i have the proble again, and now i tried to change Build System -> Legacy build system
i have the next error message 
![image](https://user-images.githubusercontent.com/36398735/120445241-15e5fb80-c391-11eb-8813-447f355dc2b6.png)

**Comment by triniwiz** [comment]
@PetroSuch the new version of the socket.io client has a min of ios 10 , which seems to be the error there

**Comment by ihor-lev** [comment]
Great tip from @triniwiz. In other words, we have to make sure that ios platform target is up-to-date. I found in my project that it's stored in `platforms/ios/Podfile`:

```
platform :ios, '9.0'
```

However the platforms folder is rewritten all the time. I'm not sure where to put it on `App_Resources` to make it permanent.

**Comment by PetroSuch** [comment]
@triniwiz, thanks for you answer, but i returned the Build system -> Default
and had same error, Framework not found....

afterwards, i reinstlled  my project, and i built it successful
