### ISSUE TITLE
operators.share is not a function

### ISSUE THREAD

**Issue by tscislo** [NativeScript/NativeScript#6574]
After migration to Angular 6.2 from 5.0 my project complies however it throws an error in launch time.
Here is my package.json
```
{
"nativescript": {
    "id": "eu.scislo.ScanAndFind",
    "tns-ios": {
      "version": "3.2.0"
    },
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.0.0",
    "@types/lodash": "^4.14.118",
    "animate.css": "^3.6.1",
    "lodash": "~4.17.11",
    "nativescript-admob": "^1.3.2",
    "nativescript-angular": "~6.2.0",
    "nativescript-barcodescanner": "^2.6.1",
    "nativescript-dev-sass": "^1.3.0",
    "nativescript-google-analytics": "^0.4.4",
    "nativescript-i18n": "^0.2.4",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ng2-fonticon": "^1.3.4",
    "nativescript-secure-storage": "^2.2.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.3.3",
    "tns-core-modules": "^4.2.1",
    "tns-platform-declarations": "^4.2.1",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.0.0",
    "@ngtools/webpack": "~1.8.2",
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.3",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "https://registry.npmjs.org/nativescript-dev-sass/-/nativescript-dev-sass-1.2.0.tgz",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "sass-loader": "~6.0.6",
    "typescript": "~2.7.2",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
```

**Comment by tsonevn** [comment]
Hi @tscislo,
I noticed that you are using an old tns-core-modules. Can you try updating the NativeScript CLI and the modules as well on your side? Check out the update instruction [here](https://docs.nativescript.org/releases/upgrade-instructions). 
If the problem persists, please build the project with `tns run <platform_name> --log trace` and send us the full log from the console. Also, it will help if you can send us the project.

**Comment by tsonevn** [comment]
Issue moved to [NativeScript/nativescript-angular #1616](https://github.com/NativeScript/nativescript-angular/issues/1616) via [**ZenHub**](https://www.zenhub.com/)

**Comment by tscislo** [comment]
Unfortunately after upgrading to    
"tns-core-modules": "^5.0.3",
"tns-platform-declarations": "^5.0.3"
error does not go away.
