### ISSUE TITLE
file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:134:31: JS ERROR TypeError: cv._eachLayoutView is not a function. (In 'cv._eachLayoutView', 'cv._eachLayoutView' is undefined)

### ISSUE THREAD

**Issue by VimalKumarS** [NativeScript/NativeScript#5116]
### Which platform(s) does your issue occur on?
iOS 

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) 3.3.0
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) . 3.2.0
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) 3.1.0
- Plugin(s): 

"dependencies": {
    "@angular/animations": "4.4.4",
    "@angular/common": "4.4.4",
    "@angular/compiler": "4.4.4",
    "@angular/core": "4.4.4",
    "@angular/forms": "4.4.4",
    "@angular/http": "4.4.4",
    "@angular/platform-browser": "4.4.4",
    "@angular/platform-browser-dynamic": "4.4.4",
    "@angular/router": "4.4.4",
    "nativescript-angular": "4.4.1",
    "nativescript-feedback": "^1.0.6",
    "nativescript-fingerprint-auth": "^4.0.1",
    "nativescript-fresco": "^3.0.2",
    "nativescript-intl": "^3.0.0",
    "nativescript-orientation": "^1.6.1",
    "nativescript-plugin-firebase": "^4.1.1",
    "nativescript-pro-ui": "^3.2.0",
    "nativescript-pulltorefresh": "^2.0.2",
    "nativescript-secure-storage": "^2.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-unit-test-runner": "^0.3.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "^3.2.0",
    "unzip-response": "^3.0.0",
    "zone.js": "~0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.4.4",
    "@ngtools/webpack": "~1.5.3",
    "@types/jasmine": "^2.6.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.0.1",
    "cross-env": "^5.0.5",
    "extract-text-webpack-plugin": "~3.0.0",
    "fs": "0.0.1-security",
    "jasmine-core": "^2.7.0",
    "karma": "^1.7.0",
    "karma-jasmine": "^1.1.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mkdirp": "^0.5.1",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.0",
    "nativescript-dev-webpack": "^0.7.3",
    "path": "^0.12.7",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tns-platform-declarations": "3.2.0",
    "typescript": "~2.2.1",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
file:///app/tns_modules/tns-core-modules/ui/layouts/layout-base-common.js:134:31: JS ERROR TypeError: cv._eachLayoutView is not a function. (In 'cv._eachLayoutView', 'cv._eachLayoutView' is undefined)

**Comment by tsonevn** [comment]
Hi @VimalKumarS,
Thank you for contacting us.
Could you provide some more info about the problem and steps for reproduce? It would help if you could also send us sample project or at least code snippets, which could be used for recreating this scenario.

Something that I notice is that you are using a different version of NativeScript CLI runtime and modules. Regarding that, you could try upgrading the modules and runtime to version 3.3, while following the below-attached steps.
1. change the `tns-core-modules`  version to `3.3.0` in the project package.json file
2. delete `node_modules` folder
3. remove platform with `tns platform remove ios`
4. add platform again with  `tns platform add ios` and verify that the `tns-ios` is version 3.3.0 in the package.json
5. start the project with `tns run ios`

**Comment by VimalKumarS** [comment]
this happen when i upgraded from 3.1.3 to 3.3. 
I ran tns updated under project folder i was able to ran it, but chrome debugger breaks, websocket connection breaks, i posted on https://github.com/NativeScript/nativescript-cli/issues/2542 .

I am closing this issue.

**Comment by SamuelReeder** [comment]
Hello,

I ran into this same issues and cannot seem to resolve it. I am running on 3.3 atm and the issues is only appearing on iOS. Do we have any ideas to a solution?
