### ISSUE TITLE
Android Error on setupExitAndPopEnterAnimation method. 

### ISSUE THREAD

**Issue by saeb-panahifar** [NativeScript/NativeScript#8183]
**Environment**
Provide version numbers for the following components (information can be retrieved by running tns info in your project folder or by inspecting the package.json of the project):
 - Nativescript : 6.2.2
 - tns-core-modules: 6.2.3
 - tns-android: 6.2.0

**Describe the bug**

**Call Stack :** 
An uncaught Exception occurred on "main" thread.
Calling js method onViewAttachedToWindow failed
Error: java.lang.NoSuchMethodError: no static method "Landroid/animation/Animator;.addListener(Landroid/animation/Animator$AnimatorListener;)V"
StackTrace:
setupExitAndPopEnterAnimation(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:105220:18)
	at setupAllAnimation(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:105200:5)
	at _setAndroidFragmentTransitions(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:105139:13)
	at push.../node_modules/@nativescript/core/ui/frame/frame.js.Frame._navigateCore(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:106649:32)
	at push.../node_modules/@nativescript/core/ui/frame/frame-common.js.FrameBase.performNavigation(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:105973:14)
	at push.../node_modules/@nativescript/core/ui/frame/frame-common.js.FrameBase._processNextNavigationEntry(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:105964:22)
	at push.../node_modules/@nativescript/core/ui/frame/frame.js.Frame._processNextNavigationEntry(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:106491:58)
	at push.../node_modules/@nativescript/core/ui/frame/frame.js.Frame._onAttachedToWindow(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:106459:14)
	at AttachListener.onViewAttachedToWindow(file:///data/data/com.muglabb.muglakent/files/app/vendor.js:106370:27)
	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1286)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:1173)
	at com.tns.Runtime.callJSMethod(Runtime.java:1160)
	at com.tns.Runtime.callJSMethod(Runtime.java:1138)
	at com.tns.Runtime.callJSMethod(Runtime.java:1134)
	at com.tns.gen.java.lang.Object_vendor_106364_36_AttachListener.onViewAttachedToWindow(Object_vendor_106364_36_AttachListener.java:18)
	at android.view.View.dispatchAttachedToWindow(View.java:18370)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3397)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3404)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1770)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1468)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7208)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
	at android.view.Choreographer.doCallbacks(Choreographer.java:816)
	at android.view.Choreographer.doFrame(Choreographer.java:751)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6694)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.NoSuchMethodError: no static method "Landroid/animation/Animator;.addListener(Landroid/animation/Animator$AnimatorListener;)V"
	... 30 more

**To Reproduce**
`tns run android`

**Expected behavior**
It should run app on device. 

**Additional context**
The source code works on 6.1.0 perfectly but doesn't work in 6.2.2

**Comment by NickIliev** [comment]
@saeb-panahifar when receiving the error, are you using a specific project or a template project? Please consider proving a demo project or [Playground ](https://play.nativescript.org/)that can reproduce the issue.

**Comment by saeb-panahifar** [comment]
I'm using a specific project. This is the package.config file that I used in project. 
```
{
  "nativescript": {
    "id": "XXX",
    "tns-android": {
      "version": "6.2.0"
    },
    "tns-ios": {
      "version": "6.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~8.2.0",
    "@angular/common": "~8.2.0",
    "@angular/compiler": "~8.2.0",
    "@angular/core": "~8.2.0",
    "@angular/forms": "~8.2.0",
    "@angular/platform-browser": "~8.2.0",
    "@angular/platform-browser-dynamic": "~8.2.0",
    "@angular/router": "~8.2.0",
    "@auth0/angular-jwt": "^3.0.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@nstudio/nativescript-cardview": "^1.0.0",
    "@nstudio/nativescript-pulltorefresh": "^1.0.1",
    "@nstudio/nativescript-snackbar": "^1.0.0",
    "jsonwebtoken": "^8.5.1",
    "nativescript-advanced-webview": "^4.0.1",
    "nativescript-angular": "~8.2.0",
    "nativescript-barcodescanner": "^3.3.2",
    "nativescript-camera": "^4.5.0",
    "nativescript-clipboard": "^1.2.0",
    "nativescript-drop-down": "^5.0.4",
    "nativescript-geolocation": "^5.1.0",
    "nativescript-google-maps-sdk": "^2.7.0",
    "nativescript-kontaktio": "^1.0.0",
    "nativescript-local-notifications": "^4.0.1",
    "nativescript-nfc": "^4.0.4",
    "nativescript-oauth2": "^2.1.1",
    "nativescript-pager": "11.0.11",
    "nativescript-permissions": "^1.3.7",
    "nativescript-plugin-firebase": "^10.0.0",
    "nativescript-social-share": "^1.5.2",
    "nativescript-star-ratings": "^1.0.0",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-sidedrawer": "~7.0.0",
    "nativescript-urlhandler": "^1.3.0",
    "reflect-metadata": "~0.1.12",
    "rxjs": "^6.4.0",
    "tns-core-modules": "~6.2.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~8.2.0",
    "tns-platform-declarations": "^6.1.0",
    "@ngtools/webpack": "~8.2.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.3.0",
    "node-sass": "^4.7.1",
    "tslint": "~5.19.0",
    "typescript": "~3.5.3"
  },
  "gitHead": "5fa096231ded5351b53700f0d111d60160e52ebc",
  "readme": "NativeScript Application"
}

```

**Comment by NickIliev** [comment]
@saeb-panahifar the package.json is not enough to reproduce the issue - can you create a demo project?

**Comment by tommag21** [comment]
@saeb-panahifar looks like it's an issue with nativescript-advanced-webview. Tracked [here](https://github.com/bradmartin/nativescript-advanced-webview/issues/48)
