### ISSUE TITLE
nativescript-plugin-firebase Google authentication error

### ISSUE THREAD

**Issue by tomcatmwi** [NativeScript/NativeScript#6105]
I'm building a NativeScript app with EddyVerbruggen's `nativescript-plugin-firebase` plugin handling the logins. I've received the following error message on the console:

```
JS: PLEASE REPORT THIS AT https://github.com/NativeScript/NativeScript/issues: Tried to serialize an unsupported type: javaObj.getClass().getName(), error: TypeError: javaObj.entrySet is not a function
```
So I reported this. The message appears six times upon calling the plugin's login function. I'm not doing anything but what's in the manual.

```
firebase.login({
            type: firebase.LoginType.GOOGLE
        }).then(
            (result) => {
                console.log('[AppComponent] Successful login');
            },
            (errorMessage) => {
                console.log('[AppComponent] Error: ', errorMessage);
            }
        );
```

Despite the error message, the login works, and no other functions produce similar messages.

I'm working on Windows 10, `{N}` version 4.1.0.

**Comment by tsonevn** [comment]
Hi @tomcatmwi,
Can you provide more info about the error, which you are facing and the NativeScript template, which you have used? It will also help if you give a sample project, which can be used for debugging.

**Comment by tomcatmwi** [comment]
Take the entire project. It's very rudimentary at this point, only a Google
sign-in service, but that's exactly what you need.

https://github.com/tomcatmwi/pocketvault

The `login()` function in `firebase-auth.service.ts` produces this glitch.

**Comment by NickIliev** [comment]
@tomcatmwi the issue seems related to nativescript-plugin-firebase - closing as duplicate to [https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/803](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/803)
