### ISSUE TITLE
Error after upgrade to 2.2

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/NativeScript#3121]
Hello,

I recently upgraded to NS 2.2 from 2.0 and now I am having trouble with loading the nativescript-push-notifications plugin in Android. Everything works fine in iOS, but in android I am getting the following error:

Error: Cannot find module "nativescript-push-notifications"

The error is in everlive.all.min.js line 339. I am using Everilve SDK version 1.8.1

Here is what my package.json look like:

{
"nativescript": {
"id": "com.macfarlanegp.awlmobilenative"
},
"dependencies": {
"moment": "2.14.1",
"moment-timezone": "0.5.5",
"nativescript-background-http": "2.4.0",
"nativescript-email": "1.3.3",
"nativescript-intl": "0.0.4",
"nativescript-iqkeyboardmanager": "1.0.0",
"nativescript-loading-indicator": "2.0.1",
"nativescript-maskedinput": "0.0.3",
"nativescript-pdf-view": "1.2.0",
"nativescript-phone": "1.2.3",
"nativescript-social-share": "1.3.1",
"nativescript-telerik-ui": "1.5.0",
"nativescript-touchid": "2.1.0",
"tns-core-modules": "2.4.0",
"nativescript-push-notifications": "0.0.15"
},
"devDependencies": {}
}

Any help is greatly appreciated.
Thank you.

NOTE:  I posted this on the plugin's page as well, but I wanted to post it here as well since I am not sure where this issue is originating.

**Comment by NickIliev** [comment]
Hey @dpdragnev 

Thank you for reporting this issue - indeed the  right place for this is in the plugin's repository as this is a plugin specific issue, so I will close this one as a duplicate your original one [here](https://github.com/NativeScript/push-plugin/issues/65).

We will update the issue, once we have additional information about the case and the solution.

Duplicate to [https://github.com/NativeScript/push-plugin/issues/65](https://github.com/NativeScript/push-plugin/issues/65)

As a side note, I would recommend updating your NativeScript-CLI to the latest version or at least to be synced with the **tns-core-module** version in order to prevent any mismatching. As in your package.json the current version of tns-core-modules is 2.4.0 the best practice is to update your runtime as well to the latest official release.
