### ISSUE TITLE
nativescript-i18n plugin not working after upgrading {N} to 3.0 rc.1

### ISSUE THREAD

**Issue by NathakornJ** [NativeScript/NativeScript#4012]
Dear friend, we, the rest of the NativeScript community really
appreciate your feedback! While we are doing all we can to take care of every
issue, sometimes we get overwhelmed. Because of that, we will consider issues
that are not constructive or problems that cannot be reproduced "dead".
Additionally, we will treat feature requests or bug reports with unanswered
questions regarding the behavior/reproduction for more than 20 days "dead". All
"dead" issues will get closed.

## Please, provide the details below:
I upgraded my {N} project from version 2.5.4 to 3.0 RC.1. Then run tns build android. It failed. Following is the error message

Executing before-prepare hook from D:\Source\NS\Hallo\hooks\before-prepare\nativescript-dev-android-snapshot.js
Executing before-prepare hook from D:\Source\NS\Hallo\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
node_modules/nativescript-i18n/angular.ts(20,23): error TS2339: Property 'L' does not exist on type 'Global'.

TypeScript compiler failed with exit code 1

### Did you verify this is a real problem by searching [Stack Overflow](http://stackoverflow.com/questions/tagged/nativescript) and the [other open issues in this repo](https://github.com/NativeScript/nativescript/issues)?

I had been searching Google for hours but could not find any solutions and instruction

### Tell us about the problem
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

The problem is related to file nativescript-i18n/angular.ts(20,23). 
class L implements PipeTransform {
    transform(value: string, ...more: string[]): string {
        return global.L(value, ...more); //////////L is undefined
    }
}

In this file, it require('./i18n') but I guess that this does not work.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: (run `tns --version` to fetch it) >>>>3.0.0-rc.1
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project) >>>>>3.0.0-rc.2
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the
`package.json` file of your project) >>>>> tns-android:{ version: 3.0.0-rc.1}
- Plugin(s): (look for the version number in the `package.json` file of your
project) >>>> "nativescript-i18n": "^0.1.6"

### Please tell us how to recreate the issue in as much detail as possible.
1. tns plugin add nativescript-i18n@latest
2. Following examples on https://github.com/rborn/nativescript-i18n
3. tns build android

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
No

**Comment by tsonevn** [comment]
Hi @NathakornJ,
Thank you for reporting this issue,
I review the plugin and indeed it seems to not been supported with NativeScript @rc modules. However, this plugin is created by one of our community members. On that point, you could keep track on the issue [here ](https://github.com/rborn/nativescript-i18n/issues/47), where you could vote for this to be fixed and give your additional info about the problem, which you are facing.
