### ISSUE TITLE
Need Help: Webpack not working for NativeScript 3 and Angular 4

### ISSUE THREAD

**Issue by NathakornJ** [NativeScript/NativeScript#4439]
I am working on webpack for a {N} 3.0 + Angular 4 project according to instructions from https://docs.nativescript.org/tooling/bundling-with-webpack. 
When I run >> **npm run build-android-bundle** OR **npm run start-android-bundle**, it excepts with following error:

> @ build-android-bundle D:\Source\NS\Hallo
> npm run ns-bundle --android --build-app

> @ ns-bundle D:\Source\NS\Hallo
> ns-bundle

Running webpack for android...
module.js:471
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Source\NS\Hallo\webpack.config.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathakorn\AppData\Roaming\npm-cache\_logs\2017-06-22T06_44_34_971Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build-android-bundle: `npm run ns-bundle --android --build-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nathakorn\AppData\Roaming\npm-cache\_logs\2017-06-22T06_44_35_008Z-debug.log

**Here is my package.json file:**
"dependencies": {
    "@angular/animations": "^4.1.2",
    "@angular/common": "^4.1.3",
    "@angular/compiler": "^4.1.3",
    "@angular/core": "^4.1.3",
    "@angular/forms": "^4.1.3",
    "@angular/http": "^4.1.3",
    "@angular/platform-browser": "^4.1.3",
    "@angular/platform-browser-dynamic": "^4.1.2",
    "@angular/router": "^4.1.3",
    "faker": "^4.1.0",
    "nativescript-angular": "^3.0.0",
    "nativescript-angular-snapshot": "3.0.0-5.5.372.32",
    "nativescript-barcodescanner": "^2.5.0",
    "nativescript-camera": "^3.0.0",
    "nativescript-drop-down": "^3.0.2",
    "nativescript-emoji": "^1.1.1",
    "nativescript-grid-view": "^3.0.0",
    "nativescript-image-file": "file:local-plugins\\nativescript-image-file",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-ripple": "^2.0.0",
    "nativescript-screen": "file:local-plugins\\nativescript-screen",
    "nativescript-social-share": "^1.3.2",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-videoplayer": "^3.0.7",
    "nativescript-web-image-cache": "^4.1.0",
    "nativescript-zoomable-image": "file:local-plugins\\nativescript-zoomable-image",
    "nativescript-zxing": "^1.5.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.4.0",
    "thenby": "^1.2.3",
    "tns-core-modules": "^3.0.1",
    "tns-platform-declarations": "^3.0.1",
    "zone.js": "^0.8.12"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^4.1.3",
    "@ngtools/webpack": "~1.4.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "^0.4.5",
    "nativescript-dev-webpack": "^0.6.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "typescript": "~2.2.1",
    "webpack": "~2.6.1",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app"
  }

**Comment by tsonevn** [comment]
This issue was moved to NativeScript/nativescript-dev-webpack#198
