### ISSUE TITLE
Can't access companion from aar lib build with Kotlin 1.50 

### ISSUE THREAD

**Issue by quocman-sutrix** [NativeScript/NativeScript#9431]
Environment
Provide version numbers for the following components (information can be retrieved by running tns info in your project folder or by inspecting the package.json of the project):

CLI: 8.0.2
Please see demo-angular from here:
https://github.com/NativeScript/nativescript-ui-charts/tree/master/demo-angular

Describe the bug
I am trying to update an Android library to support for Kotlin 1.5.0. I exported the aar successfully and it's working when I integrate it into Native Project (I can even access the companion via NativeScriptApplication.java). But in JS it keep saying the getInstance() is not a function.

To Reproduce
1. Build a hello world aar with companion object and compile it using Kotlin 1.5.0.
2. Add the aar to NativeScript hello world plugin.
3. Try to run the demo and call a function from companion object.

Expected behavior
The function from companion object should be callable

**Comment by triniwiz** [comment]
There are some issues with 1.5.x I would build with the latest 1.4.x for now also you should be able to use the method like a regular static w/o using Companion , another thing you can do is pass the aar through the .d.ts generator for android . Keep in mind you can always do console.dir(theNativeObject) to see the exposed methods/props (would be limited in the cli)

**Comment by quocman-sutrix** [comment]
Thanks for suggestion @triniwiz . I will try.

**Comment by quocman-sutrix** [comment]
Hi @triniwiz when I tried to console.dir I got this 

JS: ==== object dump start ====
JS: extend()
JS: null()
JS: class: class com.company.alib.Collector$Companion
JS: ==== object dump end ====

Any suggestion to access the Companion ? Looks like it's not null it was there.

**Comment by triniwiz** [comment]
console.dir(nativeObject.Companion) will log what it contains but I have a feeling it will contain about the same info as this

**Comment by quocman-sutrix** [comment]
Yes I used console.dir(nativeObject.Companion) and that is what it returned.

**Comment by quocman-sutrix** [comment]
This is what it showed when I console.dir(nativeObject.Companion) the AAR built with Kotlin 1.4.x. 

JS: ==== object dump start ====
JS: constructor()
JS: getInstance()
JS: to()
JS: <init>()
JS: clone()
JS: equals()
JS: finalize()
JS: getClass()
JS: hashCode()
JS: notify()
JS: notifyAll()
JS: toString()
JS: wait()
JS: ==== object dump end ====

**Comment by triniwiz** [comment]
Use 1.4.x for now
