### ISSUE TITLE
File not found - node_modules/nativescript-ui-sidedrawer/references.d.ts:4:22

### ISSUE THREAD

**Issue by etelvinacunha** [NativeScript/NativeScript#9082]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 7.0.11
 - Cross-platform modules:
 - Android Runtime: 7.0.0
 - iOS Runtime:7.0.6
 - XCode Version:12.2
 - Plugin(s):

**Describe the bug**~
After migrating the natiscript from 6.5.2 to 7 and after change the path on node_modules/nativescript-ui-sidedrawer/references.d.ts

old path /// <referencepath="./node_modules/nativescript-ui-core/android.d.ts"/>
new path : ///<referencepath="../nativescript-ui-core/android.d.ts"/> 

when we make clean and after build, sometimes the changes are reverted to the old ones.
we can't reproduce this everytime , it's happens from time to time.

 **one of the errors**
node_modules/nativescript-ui-sidedrawer/references.d.ts:4:22 - error TS6053: File '/Users/work/project/med-mobile/Mobile/node_modules/nativescript-ui-sidedrawer/node_modules/nativescript-ui-core/android.d.ts' not found

any help? any idea?

**To Reproduce**
  ns build ios

**Expected behavior**
no error.

**Comment by etelvinacunha** [comment]
.
