### ISSUE TITLE
{1.5} global.moduleMerge is undefined

### ISSUE THREAD

**Issue by rclai** [NativeScript/NativeScript#1143]
I followed these upgrade instructions: https://docs.nativescript.org/upgrade-instructions

I'm getting this error after I upgraded to 1.5 and ran `tns run ios`:

```
NativeScript loaded bundle file:///System/Library/Frameworks/Foundation.framework
file:///app/tns_modules/ui/styling/background.js:3:19: JS ERROR TypeError: global.moduleMerge is not a function. (In 'global.moduleMerge(common, exports)', 'global.moduleMerge' is undefined)
1   0x12e90d -[TNSRuntime executeModule:]
2   0xfe445 main
3   0x37131873 <redacted>
```

**Comment by rclai** [comment]
Creating a brand new project and migrating files to it fixed it.

**Comment by rclai** [comment]
Never mind, the issue is still happening.

**Comment by rclai** [comment]
I am loading a module, which loads `frame`, which loads `styling` before the app launches seems to be the problem.

**Comment by hdeshev** [comment]
@rclai, are you importing the "application" module in your main module? It loads the "global" module, which contains the `moduleMerge` function. Some modules used to bring "application" in before, but we had to remove that in order to fix a [circular import issue](https://github.com/NativeScript/NativeScript/issues/948).

My guess is that adding an import for the application module in your module will fix the problem.

**Comment by rclai** [comment]
Ah okay. What I did instead is load the `application` module first before my `Meteor` module and now things are good now.
