### ISSUE TITLE
Xcode running on devices crashes with error unable to create file *.hot-update.json

### ISSUE THREAD

**Issue by isawk** [NativeScript/NativeScript#7516]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.0.0-2019-07-12-114039-13633
 - Cross-platform modules: 6.0.1
 - Android Runtime: 6.0.0
 - iOS Runtime: 6.0.0
 - Plugin(s): None added

**Describe the bug**
Running application on ios device fails with error

> Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Failed to create file at path '/var/containers/Bundle/Application/BA77C164-AE79-4EDC-947B-0B6C369EAB1A/ns6rcdebugging.app/app/04cb1cf2b2dc45ef1917.hot-update.json'

See full stack trace below, before error

<img width="871" alt="Screenshot 2019-07-14 at 04 11 35" src="https://user-images.githubusercontent.com/21027753/61178450-8775fe80-a5ed-11e9-80d4-41c27db7faf2.png">

```
2019-07-14 04:09:11.299939+0200 ns6rcdebugging[3432:1072010] *** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Error: Failed to create file at path '/var/containers/Bundle/Application/BA77C164-AE79-4EDC-947B-0B6C369EAB1A/ns6rcdebugging.app/app/04cb1cf2b2dc45ef1917.hot-update.json'
 at 
1   @file:///app/vendor.js:9436:326
2   getFile@file:///app/vendor.js:9379:150
3   getFile@file:///app/vendor.js:9436:304
4   e@file:///app/vendor.js:7209:308
5   exports@file:///app/vendor.js:7209:423
6   @file:///app/bundle.js:28:208
7   ./main.ts@file:///app/bundle.js:30:364
8   k@file:///app/runtime.js:75:17
9   n@file:///app/runtime.js:5:41
10  r@file:///app/runtime.js:4:31
11  anonymous@file:///app/bundle.js:1:183
12  evaluate@[native code]
13  moduleEvaluation@[native code]
14  promiseReactionJob@[native code]
', reason: '(null)'
*** First throw call stack:
(0x1c023927c 0x1bf4139f8 0x100e2e48c 0x100e6e028 0x100548f6c 0x1bfc8a8e0)
libc++abi.dylib: terminating with uncaught exception of type NSException

```
**To Reproduce**

```
$ tns create ${project-name} 

choose style (Angular)
choose template (Tabs)

$ cd ${project-name}
$ tns-migrate
```

Proceed to building the project as normal, below works with no errors.

`$ tns build ios --env.aot --env.uglify --env.sourceMap --bundle`

Open up project in xcode, after signing with provisioning profile etc, launch on device. All builds well but on run fails with reported error below.

**Expected behavior**
Sample application should run with no errors seems like a HMR issue, which is enabled even without --hmr flag been used.

**Sample project**
[ns-6rc-debugging](https://github.com/isawk/ns-6rc-debugging)

**Additional context**

(Unrelated to above but bug I picked up when migrating project from 5 to 6)

Also noticed existing old NS 5 projects fail to build with error

```
/Users/KOGA/Development/mobile/impact-app/node_modules/webpack-cli/bin/cli.js:244
                                throw err;
                                ^

Error: Cannot find module '@ngtools/webpack/src/transformers'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (/Users/KOGA/Development/mobile/impact-app/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
```

These are projects migrated from NS 5 to RC 6 using tns migrate command. Probably related to angular upgrade from 7 to 8.

**Comment by NickIliev** [comment]
Issue moved to [NativeScript/nativescript-cli #4846](https://github.com/NativeScript/nativescript-cli/issues/4846) via [**ZenHub**](https://www.zenhub.com/)
