### ISSUE TITLE
Frame.js Fatal Error

### ISSUE THREAD

**Issue by atchaiecommerce** [NativeScript/NativeScript#8082]
**Environment**
 - CLI: 6.2.0
 - Android Runtime: 6.2.0
 - iOS Runtime: 6.2.0
 - NativeScript-Angular: 8.0.2
 - Angular: 8.0.0
- iOS Operating System: 13.2.2
 
**Describe the bug**
I just recently upgraded to 6.2.0. I was able to make the android build work but IOS build in sidekick is producing some fatal errors that makes the app crash on load.

Package.json:
````{
  "nativescript": {
    "id": "xxxxxxxxxx",
    "tns-ios": {
      "version": "6.2.0"
    },
    "tns-android": {
      "version": "6.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "8.0.0",
    "@angular/common": "8.0.0",
    "@angular/compiler": "8.0.0",
    "@angular/core": "8.0.0",
    "@angular/forms": "8.0.0",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.0",
    "@angular/platform-browser-dynamic": "8.0.0",
    "@angular/router": "8.0.0",
    "@nstudio/nativescript-loading-indicator": "^1.0.0",
    "nativescript-angular": "8.0.2",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-datetimepicker": "^1.2.0",
    "nativescript-masked-text-field": "^4.0.1",
    "nativescript-platform-css-free": "^1.6.16",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.3.0",
    "tns-core-modules": "~6.2.0",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.0.0",
    "@nativescript/schematics": "^0.5.2",
    "@ngtools/webpack": "8.0.0",
    "codelyzer": "~4.5.0",
    "nativescript-dev-webpack": "~1.3.0",
    "tns-platform-declarations": "6.0.1",
    "tslint": "~5.11.0",
    "typescript": "3.4.5",
    "node-sass": "4.12.0"
  },
  "readme": "NativeScript Application"
}
````

Logs:
````Initializing connection
Removing all cached process handles
Sending handshake request attempt #1 to server
Creating connection to com.apple.runningboard
Handshake succeeded
Identity resolved as application<XXXXXX>
FBSWorkspace connecting to endpoint : <private>
FBSWorkspace registering source: <private>
FBSWorkspace connected to endpoint : <private>
Added observer for process assertions expiration warning: <_RBSExpirationWarningAssertion: 0x2802c6dc0; identifier: com.apple.runningboardservices.processExpirationWarningForHandle; reason: observation; valid: YES>
Retrieving resting unlock: 0
FBSWorkspace already connected to endpoint : <private>
Registering for test daemon availability notify post.
notify_get_state check indicated test daemon not ready.
CONSOLE ERROR [native code]: ERROR TypeError: undefined is not an object (evaluating 'tns_core_modules_application__WEBPACK_IMPORTED_MODULE_3__["android"].on')
CONSOLE ERROR [native code]: ERROR CONTEXT {
"view": {
"def": {
"nodeFlags": 33669121,
"rootNodeFlags": 33554433,
"nodeMatchedQueries": 0,
"flags": 0,
"nodes": [
{
"nodeIndex": 0,
"parent": null,
"renderParent": null,
"bindingIndex": 0,
"outputIndex": 0,
"checkIndex": 0,
"flags": 33554433,
"childFlags": 114688,
"directChildFlags": 114688,
"childMatchedQueries": 0,
"matchedQueries": {},
"matchedQueryIds": 0,
"references": {},
"ngContentIndex": null,
"childCount": 1,
"bindings": [],
"bindingFlags": 0,
"outputs": [],
"element": {
"ns": "",
"name": "ns-app",
"attrs": [],
"template": null,
"componentProvider": {
"nodeIndex": 1,
"parent": "[Circular]",
"renderParent": "[Circul<\M-b\M^@\M-&>
CONSOLE LOG file:///node_modules\@angular\core\fesm5\core.js:23837:0: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1032022bc NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x103238578 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x103cf0ea4 ffi_closure_SYSV_inner
4   0x103cf41b4 .Ldo_closure
5   0x1970d8670 <redacted>
6   0x1970d8914 <redacted>
7   0x197bcf958 <redacted>
8   0x19334ca4c <redacted>
9   0x19a1cfa4c <redacted>
10  0x19a1cfe9c <redacted>
11  0x19a1e25c4 <redacted>
12  0x19a127170 <redacted>
13  0x19a151f7c <redacted>
14  0x197735634 <redacted>
15  0x1935b3068 <redacted>
16  0x1935b27ec <redacted>
17  0x1935ad7ec <redacted>
18  0x1935ad084 CFRunLoopRunSpecific
19  0x19d7fb534 GSEventRunModal
20  0x19771d670 UIApplicationMain
21  0x103cf4044 ffi_call_SYSV
22  0x103cf05c8 ffi_call_int
23  0x103cf00c4 ffi_call
24  0x1031c4eb0 NativeScript::FunctionWrapper::call(JSC::ExecState*)
25  0x103cef2c8 llint_entry
26  0x103ced644 llint_entry
27  0x103ced644 llint_entry
28  0x103ced644 llint_entry
29  0x103ced644 llint_entry
30  0x103ced644 llint_entry
31  0x103ced644 llint_entry
JavaScript stack trace:
traitCollectionDidChange(file:///node_modules\@nativescript\core\ui\frame\frame.js:435:0)
at UIApplicationMain([native code])
at _start(file:///node_modules\@nativescript\core\application\application.js:324:0)
at run(file:///node_modules\@nativescript\core\application\application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules\nativescript-angular\platform-common.js:205:0)
at bootstrapApp(file:///node_modules\nativescript-angular\platform-common.js:106:0)
at bootstrapModule(file:///node_modules\nativescript-angular\platform-common.js:90:0)
at ./main.ts(file:///app/bundle.js:2197:116)
at __webpack_require__(file:///src\webpack\bootstrap:74:0)
at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
JavaScript error:
file:///node_modules\@nativescript\core\ui\frame\frame.js:435:0: JS ERROR TypeError: this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection is not a function. (In 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection(previousTraitCollection)', 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection' is undefined)
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   _start@file:///node_modules\@nativescript\core\application\application.js:324:0
2   run@file:///node_modules\@nativescript\core\application\application.js:366:0
3   bootstrapNativeScriptApp@file:///node_modules\nativescript-angular\platform-common.js:205:0
4   bootstrapApp@file:///node_modules\nativescript-angular\platform-common.js:106:0
5   bootstrapModule@file:///node_modules\nativescript-angular\platform-common.js:90:0
6   ./main.ts@file:///app/bundle.js:2197:116
7   __webpack_require__@file:///src\webpack\bootstrap:74:0
8   checkDeferredModules@file:///src\webpack\bootstrap:43:0
9   webpackJsonpCallback@file:///src\webpack\bootstrap:30:0
10  anonymous@file:///app/bundle.js:2:61
11  evaluate@[native code]
12  moduleEvaluation@:1:11
13  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection is not a function. (In 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection(previousTraitCollection)', 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection' is undefined)
at
traitCollectionDidChange(file:///node_modules\@nativescript\core\ui\frame\frame.js:435:0)
at UIApplicationMain([native code])
at _start(file:///node_modules\@nativescript\core\application\application.js:324:0)
at run(file:///node_modules\@nativescript\core\application\application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules\nativescript-angular\platform-common.js:205:0)
at bootstrapApp(file:///node_modules\nativescript-angular\platform-common.js:106:0)
at bootstrapModule(file:///node_modules\nativescript-angular\platform-common.js:90:0)
at ./main.ts(file:///app/bundle.js:2197:116)
at __webpack_require__(file:///src\webpack\bootstrap:74:0)
at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEva<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x1032454e4 sig_handler(int)
2   0x19333f424 <redacted>
3   0x193342d10 pthread_kill
4   0x1932d2a74 abort
5   0x1933ea3c8 __cxa_bad_cast
6   0x1933ea5c0 <redacted>
7   0x193351308 <redacted>
8   0x1933f7634 <redacted>
9   0x1933f6f58 __cxa_get_exception_ptr
10  0x1933f6f10 <redacted>
11  0x193351158 <redacted>
12  0x103202738 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x103238578 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
14  0x103cf0ea4 ffi_closure_SYSV_inner
15  0x103cf41b4 .Ldo_closure
16  0x1970d8670 <redacted>
17  0x1970d8914 <redacted>
18  0x197bcf958 <redacted>
19  0x19334ca4c <redacted>
20  0x19a1cfa4c <redacted>
21  0x19a1cfe9c <redacted>
22  0x19a1e25c4 <redacted>
23  0x19a127170 <redacted>
24  0x19a151f7c <redacted>
25  0x197735634 <redacted>
26  0x1935b3068 <redacted>
27  0x1935b27ec <redacted>
28  0x1935ad7ec <redacted>
29  0x1935ad084 CFRunLoopRunSpecific
30  0x19d7fb534 GSEventRunModal
31  0x19771d670 UIApplicationMain
JS Stack:
UIApplicationMain([native code])
at _start(file:///node_modules\@nativescript\core\application\application.js:324:0)
at run(file:///node_modules\@nativescript\core\application\application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules\nativescript-angular\platform-common.js:205:0)
at bootstrapApp(file:///node_modules\nativescript-angular\platform-common.js:106:0)
at bootstrapModule(file:///node_modules\nativescript-angular\platform-common.js:90:0)
at ./main.ts(file:///app/bundle.js:2197:116)
at __webpack_require__(file:///src\webpack\bootstrap:74:0)
at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at promiseReactionJob
````

**Comment by atchaiecommerce** [comment]
guys from slack are also experiencing this error. any ideas?

**Comment by MCorzo** [comment]
Hi, 
I have the same error after update my project to 6.2, please help us with this problem.

**Environment**
```
CLI: 6.2.0
Android Runtime: 6.2.0
iOS Runtime: 6.2.0
NativeScript-Angular: 8.20.0
Angular: 8.2.13
iOS Operating System: 13.2
```

**Log**

```
Task <251DA2B5-B523-4017-8FB5-4E8D473F7AE2>.<1> setting up Connection 3
tcp_output [C3.1:3] flags=[S] seq=3576673347, ack=0, win=65535 state=SYN_SENT rcv_nxt=0, snd_una=3576673347
CONSOLE LOG file:///src\app\app.module.ts:60:20: NativeScriptError: TypeError: this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection is not a function. (In 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection(previousTraitCollection)', 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection' is undefined)
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x101a7a2bc NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x101ab0578 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x102568ea4 ffi_closure_SYSV_inner
4   0x10256c1b4 .Ldo_closure
5   0x198c1ba1c <redacted>
6   0x198c1bce0 <redacted>
7   0x1996cb1d0 <redacted>
8   0x19bc1978c <redacted>
9   0x19bc1f908 <redacted>
10  0x19bc2a528 <redacted>
11  0x19bb72ed0 <redacted>
12  0x19bb9cbbc <redacted>
13  0x19924dbd4 <redacted>
14  0x19514b5f8 <redacted>
15  0x19514ad98 <redacted>
16  0x195146014 <redacted>
17  0x1951458a0 CFRunLoopRunSpecific
18  0x19f09d328 GSEventRunModal
19  0x199236768 UIApplicationMain
20  0x10256c044 ffi_call_SYSV
21  0x1025685c8 ffi_call_int
22  0x1025680c4 ffi_call
23  0x101a3ceb0 NativeScript::FunctionWrapper::call(JSC::ExecState*)
24  0x1025672c8 llint_entry
25  0x102565644 llint_entry
26  0x102565644 llint_entry
27  0x102565644 llint_entry
28  0x102565644 llint_entry
29  0x102565644 llint_entry
30  0x102565644 llint_entry
31  0x102565644 llint_entry
JavaScript stack trace:
traitCollectionDidChange(file:///node_modules\@nativescript\core\ui\core\view\view.js:829:0)
at UIApplicationMain([native code])
at _start(file:///node_modules\@nativescript\core\application\application.js:324:0)
at run(file:///node_modules\@nativescript\core\application\application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules\@nativescript\angular\platform-common.js:210:0)
at bootstrapApp(file:///node_modules\@nativescript\angular\platform-common.js:111:0)
at bootstrapModule(file:///node_modules\@nativescript\angular\platform-common.js:91:0)
at file:///app/bundle.js:7240:144
at ./main.ts(file:///app/bundle.js:7245:34)
at __webpack_require__(file:///src\webpack\bootstrap:750:0)
at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
JavaScript error:
file:///node_modules\@nativescript\core\ui\core\view\view.js:829:0: JS ERROR TypeError: this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection is not a function. (In 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection(previousTraitCollection)', 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection' is undefined)
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   _start@file:///node_modules\@nativescript\core\application\application.js:324:0
2   run@file:///node_modules\@nativescript\core\application\application.js:366:0
3   bootstrapNativeScriptApp@file:///node_modules\@nativescript\angular\platform-common.js:210:0
4   bootstrapApp@file:///node_modules\@nativescript\angular\platform-common.js:111:0
5   bootstrapModule@file:///node_modules\@nativescript\angular\platform-common.js:91:0
6   @file:///app/bundle.js:7240:144
7   ./main.ts@file:///app/bundle.js:7245:34
8   __webpack_require__@file:///src\webpack\bootstrap:750:0
9   checkDeferredModules@file:///src\webpack\bootstrap:43:0
10  webpackJsonpCallback@file:///src\webpack\bootstrap:30:0
11  anonymous@file:///app/bundle.js:2:61
12  evaluate@[native code]
13  moduleEvaluation@:1:11
14  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection is not a function. (In 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection(previousTraitCollection)', 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection' is undefined)
at
traitCollectionDidChange(file:///node_modules\@nativescript\core\ui\core\view\view.js:829:0)
at UIApplicationMain([native code])
at _start(file:///node_modules\@nativescript\core\application\application.js:324:0)
at run(file:///node_modules\@nativescript\core\application\application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules\@nativescript\angular\platform-common.js:210:0)
at bootstrapApp(file:///node_modules\@nativescript\angular\platform-common.js:111:0)
at bootstrapModule(file:///node_modules\@nativescript\angular\platform-common.js:91:0)
at file:///app/bundle.js:7240:144
at ./main.ts(file:///app/bundle.js:7245:34)
at __webpack_require__(file:///src\webpack\bootstrap:750:0)
at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at eval<\M-b\M^@\M-&>
NativeScript caught signal 6.
Native Stack:
1   0x101abd4e4 sig_handler(int)
2   0x194edc884 <redacted>
3   0x194ee1774 <redacted>
4   0x194e35844 abort
5   0x194f8e7d4 __cxa_bad_cast
6   0x194f8e9c4 <redacted>
7   0x194ef6258 <redacted>
8   0x194f9b304 <redacted>
9   0x194f9ac58 __cxa_get_exception_ptr
10  0x194f9ac18 <redacted>
11  0x194ef60d0 <redacted>
12  0x101a7a738 NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
13  0x101ab0578 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
14  0x102568ea4 ffi_closure_SYSV_inner
15  0x10256c1b4 .Ldo_closure
16  0x198c1ba1c <redacted>
17  0x198c1bce0 <redacted>
18  0x1996cb1d0 <redacted>
19  0x19bc1978c <redacted>
20  0x19bc1f908 <redacted>
21  0x19bc2a528 <redacted>
22  0x19bb72ed0 <redacted>
23  0x19bb9cbbc <redacted>
24  0x19924dbd4 <redacted>
25  0x19514b5f8 <redacted>
26  0x19514ad98 <redacted>
27  0x195146014 <redacted>
28  0x1951458a0 CFRunLoopRunSpecific
29  0x19f09d328 GSEventRunModal
30  0x199236768 UIApplicationMain
31  0x10256c044 ffi_call_SYSV
JS Stack:
UIApplicationMain([native code])
at _start(file:///node_modules\@nativescript\core\application\application.js:324:0)
at run(file:///node_modules\@nativescript\core\application\application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules\@nativescript\angular\platform-common.js:210:0)
at bootstrapApp(file:///node_modules\@nativescript\angular\platform-common.js:111:0)
at bootstrapModule(file:///node_modules\@nativescript\angular\platform-common.js:91:0)
at file:///app/bundle.js:7240:144
at ./main.ts(file:///app/bundle.js:7245:34)
at __webpack_require__(file:///src\webpack\bootstrap:750:0)
at checkDeferredModules(file:///src\webpack\bootstrap:43:0)
at webpackJsonpCallback(file:///src\webpack\bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation
at promiseReactionJob
```

**Comment by peerbits-shrujal** [comment]
Hi,
Same error after updating project to 6.2.

[Slack conversation](https://nativescriptcommunity.slack.com/archives/C0L9EJS7Q/p1573448819169800)

```
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1030262bc NativeScript::reportFatalErrorBeforeShutdown(JSC::ExecState*, JSC::Exception*, bool)
2   0x10305c578 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
3   0x103b14ea4 ffi_closure_SYSV_inner
4   0x103b181b4 .Ldo_closure
5   0x1ae6db97c <redacted>
6   0x1ae6dbc40 <redacted>
7   0x1af18b1d0 <redacted>
8   0x1b16d978c <redacted>
9   0x1b16df908 <redacted>
10  0x1b16ea528 <redacted>
11  0x1b1632ed0 <redacted>
12  0x1b165cbbc <redacted>
13  0x1aed0dbac <redacted>
14  0x1aac0b5f8 <redacted>
15  0x1aac0ad98 <redacted>
16  0x1aac06014 <redacted>
17  0x1aac058a0 CFRunLoopRunSpecific
18  0x1b4b5d328 GSEventRunModal
19  0x1aecf6740 UIApplicationMain
20  0x103b18044 ffi_call_SYSV
21  0x103b145c8 ffi_call_int
22  0x103b140c4 ffi_call
23  0x102fe8eb0 NativeScript::FunctionWrapper::call(JSC::ExecState*)
24  0x103b132c8 llint_entry
25  0x103b11644 llint_entry
26  0x103b11644 llint_entry
27  0x103b11644 llint_entry
28  0x103b11644 llint_entry
29  0x103b11644 llint_entry
30  0x103b11644 llint_entry
31  0x103b11644 llint_entry
JavaScript stack trace:
traitCollectionDidChange(file:///node_modules/@nativescript/core/ui/core/view/view.js:829:0)
at UIApplicationMain([native code])
at _start(file:///node_modules/@nativescript/core/application/application.js:324:0)
at run(file:///node_modules/@nativescript/core/application/application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules/@nativescript/angular/platform-common.js:210:0)
at bootstrapApp(file:///node_modules/@nativescript/angular/platform-common.js:111:0)
at bootstrapModule(file:///node_modules/@nativescript/angular/platform-common.js:91:0)
at file:///app/bundle.js:2165:144
at ./main.ts(file:///app/bundle.js:2170:34)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at evaluate([native code])
at moduleEvaluation([native code])
at promiseReactionJob([native code])
JavaScript error:
file:///node_modules/@nativescript/core/ui/core/view/view.js:829:0: JS ERROR TypeError: this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection is not a function. (In 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection(previousTraitCollection)', 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection' is undefined)
*** JavaScript call stack:
(
0   UIApplicationMain@[native code]
1   _start@file:///node_modules/@nativescript/core/application/application.js:324:0
2   run@file:///node_modules/@nativescript/core/application/application.js:366:0
3   bootstrapNativeScriptApp@file:///node_modules/@nativescript/angular/platform-common.js:210:0
4   bootstrapApp@file:///node_modules/@nativescript/angular/platform-common.js:111:0
5   bootstrapModule@file:///node_modules/@nativescript/angular/platform-common.js:91:0
6   @file:///app/bundle.js:2165:144
7   ./main.ts@file:///app/bundle.js:2170:34
8   __webpack_require__@file:///src/webpack/bootstrap:750:0
9   checkDeferredModules@file:///src/webpack/bootstrap:43:0
10  webpackJsonpCallback@file:///src/webpack/bootstrap:30:0
11  anonymous@file:///app/bundle.js:2:61
12  evaluate@[native code]
13  moduleEvaluation@:1:11
14  promiseReactionJob@:1:11
)
*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: TypeError: this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection is not a function. (In 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection(previousTraitCollection)', 'this.traitCollection.hasDifferentColorAppearanceComparedToTraitCollection' is undefined)
at
traitCollectionDidChange(file:///node_modules/@nativescript/core/ui/core/view/view.js:829:0)
at UIApplicationMain([native code])
at _start(file:///node_modules/@nativescript/core/application/application.js:324:0)
at run(file:///node_modules/@nativescript/core/application/application.js:366:0)
at bootstrapNativeScriptApp(file:///node_modules/@nativescript/angular/platform-common.js:210:0)
at bootstrapApp(file:///node_modules/@nativescript/angular/platform-common.js:111:0)
at bootstrapModule(file:///node_modules/@nativescript/angular/platform-common.js:91:0)
at file:///app/bundle.js:2165:144
at ./main.ts(file:///app/bundle.js:2170:34)
at __webpack_require__(file:///src/webpack/bootstrap:750:0)
at checkDeferredModules(file:///src/webpack/bootstrap:43:0)
at webpackJsonpCallback(file:///src/webpack/bootstrap:30:0)
at anonymous(file:///app/bundle.js:2:61)
at eval<\M-b\M^@\M-&>
```

**Comment by NickIliev** [comment]
@atchaiecommerce @MCorzo @peerbits-shrujal the issue is indeed a bug and will be fixed via[ this PR](https://github.com/NativeScript/NativeScript/pull/8093).

**Comment by janoshrubos** [comment]
Closing this issue since it was fixed in #8093. 
If this error is still relevant, feel free to open a new issue!
