### ISSUE TITLE
Declarative UI Observable(?) Function Warning Regression in 2.4

### ISSUE THREAD

**Issue by NathanaelA** [NativeScript/NativeScript#3096]
## Please, provide the details below:

Adding a filter/function off of `application.resources` is and using it in a temporary binding break when overwriting the .text value later.    I don't fully understand why it throws and error; but it does throw an error/warning in 2.4 where it did work fine in 2.2 .
It will throw the error:  `Cannot find function or filter: FUNCTIONNAME`   

This is probably a corner case; but it is a valid case; I use the Observable syntax in XML to generate a listview full of items and values against some functions.  However when data is updated on a row I actually manually update the button text labels (i.e. the underlying data is NOT an observable, so no actual binding should have occurred).   When I update the .text of the Button field it throws that error. 

### Did you verify this is a real problem by searching 
Yes

### Which platform(s) does your issue occur on?
Android  (Maybe Both)

### Please provide the following version numbers that your issue occurs with:
 nativescript           │ 2.3.0
 tns-core-modules │ 2.5.0-2016-11-14-4775
 tns-android          │ 2.5.0-next-2016-11-07-1363

### Please tell us how to recreate the issue in as much detail as possible.

In app.js assign a new application.resource.buttonLabels= function(a, b) { return 'data '+b+' label'+a; };
In your xml do 
<Button id="btn" text="{{btnValue | buttonLabels(3) }}" tap="increase"/>

In your screen add the code:
Global: 
  var data = {btnValue: "Hi"};
  var page;
onNavigatingTo: 
  page = args.object;  
  page.bindingContext  data;

export.increase = function() {
  var btn = page.getViewById('btn');
  btn.text = "New Value "+"Hello";
};

This code is without a listview;  I was trying for a simple example.   I don't know if the list view is required to trigger the error; if it is, then the increase() function is passed the button that is supposed to change so that you don't actually have to use getViewById, just use args.object.  

I can reliably cause this "error" inside a fairly complex layout and it occurs on every single button that uses this type of code, on the 2.4 version as of 2016/11/15.
