### ISSUE TITLE
Data not loading on some views

### ISSUE THREAD

**Issue by dbay920** [NativeScript/NativeScript#5777]
### Tell us about the problem
On first load of app after install, the data for is not loading on my two of my app's views (see screenshots). I was having a similar problem before - #5691 -  which was resolved after updating nativescript-geolocation-services to 4.2.6. but the problem seems to be back on these two views.

![screenshot_20180503-172302_myphn](https://user-images.githubusercontent.com/4195311/39603553-e997ce26-4ef6-11e8-8238-4631c1fc1b1a.jpg)
![screenshot_20180503-172257_myphn](https://user-images.githubusercontent.com/4195311/39603554-eb756b22-4ef6-11e8-9c83-dfa07b22f86b.jpg)

Screenshots show distance and alphabetical tabs' data not loading. The data loads after closing and re-opening the app.

### Which platform(s) does your issue occur on?
Android

### Please provide the following version numbers that your issue occurs with:
- CLI: 3.4.2
- Cross-platform modules: 4.0.0
- Runtime(s): Android: 3.4.2
- Plugin(s): nativescript-geolocation-services v. 4.2.6

### Please tell us how to recreate the issue in as much detail as possible.
[branch repo on github](https://github.com/dbay920/phn-app/tree/android-fixes/MyPHN)

### Is there code involved? If so, please share the minimal amount of code needed to recreate the problem.
I'm seeing this in terminal:
`Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.hb>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/SafeBrowsingResponse;`

**Comment by dbay920** [comment]
#5691 was previous issue that was similar

**Comment by NickIliev** [comment]
@dbay920 the issue seems to be related to the old one as in the linked repository the package.json is still referring to the old version of nativescript-geolocation and not to  4.2.6. You are also using `package-lock` file, which you might consider removing before applying the newer versions and running `npm i`. As a general advice for both performance and compatibility with the latest versions of all plugins, you might want to migrate the application to the latest NativeScript modules, runtimes and `nativescript-angular` versions

**Comment by RoyiNamir** [comment]
@dbay920 
@NickIliev 




I'm getting this after upgrading from 3.4.1 to 4 [**in this plugin**](https://github.com/EddyVerbruggen/nativescript-admob/issues/30) .

After testing - It's not related to the plugin IMHO but to the version 4.
I've already remove the lock file
